---
title: "envs193ds_hw3"
author: "Hibah Ganie"
date: "2025-05-28"
output: html_document
---

## [Hibah's Github Repository](https://github.com/hibdawg/ENVS-193DS_homework-03)

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Reading In Packages and Data}
library(tidyverse) # General Use
library(janitor) # Cleaning data Frames
library(dplyr) # Mutate columns
library(lubridate) # make dealing with dates easier
library(here) # File Organization
library(readxl) # reading .xlsx files
library(ggeffects) # generating model predictions
library(gtsummary) # generating summary tables for models 
library(ggplot2)
library(hms) # working with times
library(readr) # Reads in Data 
library(xfun)
library(gt)

my_data <- read_csv(here("data", "hibdata2.csv")) # read in my data
```

```{r Cleaning My Data}
clean_hibdata <- my_data |> 
  clean_names() |> 
  rename(
    exam_week = finals_week,
    shared = shared_table,
    floor = floor_level,
    day = dayw) |> 
   mutate(
    duration = as_hms(duration),
    duration_seconds = as.numeric(duration),
    duration_category = if_else(duration_seconds < 4500, "short", "long"),
    duration_category = as.factor(duration_category),
    outlet = as.factor(outlet),
    shared = as.factor(shared),
    floor = as.factor(floor),
    exam_week = as.factor(exam_week),
    week = factor(week,
                  ordered = TRUE,
                  levels = c("1", "2","3", "4", "5", "6", "7", "8", "9", "10")
    ),
    day = factor(day,
                 ordered = TRUE,
                 levels = c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday")
                 )
  ) |> 
  select(time, scouting, exam_week, week, outlet, shared, duration, floor, day, duration_category)

```


## Part 2. Problems

## Problem 1. Personal Data

# Data Summarizing

#A.  
[I could compare how the duration of events follows my class schedule and see how I have shorter events on days where I have class due to gaps in my schedule where I study. I also want to compare how total study time based on weeks increase, or may taper off as I struggle to find a spot in the library and may need to go elsewhere to study.]

#B.  
```{r Data Visualization}
ggplot(
  clean_hibdata, # Select Clean Datafram
  aes(x = day, # X axis
      fill = duration_category) # based on Category of Session Length
) +
  geom_bar(position = "dodge") + # Bar Graph
  labs( # Add labels
    title = "Short vs Long Weekly Study Sessions 4/20/25 - 5/29/25", # title of Graph
    x = "Days of the Week", # X Label
    y = "Number of Sessions", # Y Lael
    fill = "Session Type", # Differentiate Based on category
    caption = "Study Session Data From Hibah Ganie"
  ) + 
  theme_classic() + # choose theme!
  scale_fill_manual( # mannually change colors 
    values = c("short" = "pink", # pink
               "long" = "#223291")) # orange
```

#C.
[Visualizing UCSB Library Study session Data by category: Long, Short, based on threshold of 1 hour and 30 minutes throughout the week. Trends in shorter, more frequent sessions are common in the beginning of the week and often end in long frequent session specifically on Sunday.]

#D.
```{r}

hibtable <- clean_hibdata |> 
  select(day, duration_category) |> 
  tbl_summary(
    by = day,
    statistic = all_categorical() ~ "{n}",
    label = list(duration_category ~ "Session Type")
  ) |> 
  bold_labels() 

hibtable_gt <- hibtable |> 
  as_gt() |> 
  tab_header(
    title = md("**Weekly Study Session Count by Day and Type**")
  ) |> 
  tab_style(
    style = cell_text(color = "white", weight = "bold"),
    locations = cells_title(groups = "title")
  ) |> 
  tab_options(
    heading.background.color = "darkslateblue"
  )

hibtable_gt
```

